#!/bin/sh

if -x /opt/qget/QGetServer; then
	killall -9 QGetServer > /dev/null 2>&1
	(cd /opt/qget && ./QGetServer > /dev/null 2>&1 &)
	sleep 1
	(cd /opt/qget && ./QGetClient > /dev/null 2>&1)
	killall -9 QGetServer > /dev/null 2>&1
	exit
fi

if -x /opt/qget/QgetServer; then
	killall -9 QgetServer > /dev/null 2>&1
	(cd /opt/qget && ./QgetServer > /dev/null 2>&1 &)
	sleep 1
	(cd /opt/qget && ./QgetClient > /dev/null 2>&1)
	killall -9 QgetServer > /dev/null 2>&1
	exit
fi

echo "QGet executable not found."
